apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: isd4kejae-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: isd4kejae-go 
  name: isd4kejae-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: isd4kejae-go 
